name: Pull Requests - auto-assign
on: pull_request_target
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.4
        with:
          configuration-path: ".github/auto_assign.yml"
